### ISSUE TITLE
As an API user, I want to know how long a request took to complete

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#105]
## 💪 Motivation
...so that I can use this for metrics purposes and/or for a better understanding of how to improve my access to the API from a client.

## ⚖️ Acceptance Criteria
**Given** a running API and registry with data ingested
**When I perform** a query to the API
**Then I expect** the response to include a `took` field with the amount of time it takes for the query to be pushed to the registry, parsed by the API service, and then tagged with with the time right before the response is returned by the API service

## ⚙️ Engineering Details

Similar to ESDIS CMR response, something like:
```
{
  "hits" : 2,
  "took" : 11,
  "items" : [ {
...
```

seems like this is tightly coupled with #68 so figured I would add to this sprint as well

**Comment by al-niessner** [comment]
Waiting for #87

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

"took" is in what units? If seconds, then float? It is currently number of milliseconds, since most requests are less than a second, and documented as such but could look strange if the did-not-read-the-manual assumption is seconds.

**Comment by jordanpadams** [comment]
resolved per https://github.com/NASA-PDS/pds-api/issues/87 and https://github.com/NASA-PDS/pds-api/commit/7fe91eb0438c90cf93713ad1053418815036136a
