### ISSUE TITLE
Update API endpoints to use `identifier` instead of `lidvid`

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#108]
## 💪 Motivation
Considering the current API supports both `endpoint/{lid}` and `endpoint/{lidvid}`, it is confusing that the API spec specifically says `endpoint/{lidvid}`. Additionally, with the completion of #74 , specifying `latest` and `all` doesn't make sense in the context of `endpoint/{lidvid}` because the specific version of the product is implied.

## 📖 Additional Details

Update all API endpoints from `endpoint/{lidvid}` to `endpoint/{identifier}`. For the description of identifier, we can note that this is `lidvid` or `lid`.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl any thoughts on this welcome.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams @tdddblog I would use 'id' to match what we use in the reponse format so that it super clear to the user that we are speaking of the same thing.
