### ISSUE TITLE
Extend application/pds4+json support to all endpoints

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#110]
## 💪 Motivation
...so that I can utilize the application/pds4+json across the entire API.

## 📖 Additional Details

#101 implemented the `application/pds4+json` response format for some of the endpoints, this should expound upon that to all endpoints.

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect** 

## ⚙️ Engineering Details

Application requirements:
:unicorn: #101

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

I have walked the code and it appears that the only changes required are in the API on swagger. Done.

WebMVCC seems to have the necessary links so that all endpoints will user the correct serializer.
