### ISSUE TITLE
Improve PDS API Development Workflow and Versioning

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#114]
## Additional Details
Current development is very clunky between API Spec + Swagger Hub.

### Current Workflow
* update open api yaml in swaggerhub "branch"
* develop in registry-api-service
* create a branch in registry-api-service that breaks and refer to the swaggerhub "branch"

### Potential New Workflow
* Update open api yaml in Github branch
* Create PR in PDS API to enable early review of API design
* Merge PDS API PR to main
* Sync main back to Swagger Hub v0.x.x-dev
* Development on registry-api-service can happen in parallel, minimizing conflict of YAML design
* Registry-api-service may actually build via CI if new PDS API PR is merged in time

Other perks: Real versioning in OpenAPI YAML (currently using `main`), which is not really how dev versions should be versioned

**Comment by jordanpadams** [comment]
📆 October status: on schedule

**Comment by jordanpadams** [comment]
📆 November status: Delayed due to increased complexity and scope.

**Comment by jordanpadams** [comment]
:calendar: December status: delayed as initial trade study solutions have not panned out. task i spit from ongoing development efforts so no impact on B12.1

**Comment by nutjob4life** [comment]
@tloubrieu-jpl working on repository descriptions, but dependency with @jimmie. Issues with CICD, bugs have been posted.

**Comment by jordanpadams** [comment]
Completed per https://github.com/NASA-PDS/registry-api

**Comment by jordanpadams** [comment]
📆 January status: delayed an additional sprint due to increased scope. no impact on build.

**Comment by jordanpadams** [comment]
Done. all sub-tasks necessary for this build completed.
