### ISSUE TITLE
As an API user, I want a CSV response format option

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#120]
## 💪 Motivation
...so that I can query the API and get something like a PDS3 index table, e.g. https://pds-imaging.jpl.nasa.gov/data/cassini/cassini_orbiter/coiss_2025/index/index.tab which has a PDS3 label https://pds-imaging.jpl.nasa.gov/data/cassini/cassini_orbiter/coiss_2025/index/index.lbl

## ⚖️ Acceptance Criteria
**Given** a registry + API installment with 1 or more data sets ingested
**When I perform** a query of the API with response format specified as `application/csv` (or `text/csv`?)
**Then I expect** a valid CSV response to be returned

## ⚙️ Engineering Details

* Solr has a good example of a CSV response format: https://solr.apache.org/guide/7_0/response-writers.html#csv-writer-example

**Comment by tloubrieu-jpl** [comment]
The specification for csv is started there: https://github.com/NASA-PDS/pds-api/blob/main/docs/spec/response_formats.md#kvp-response-applicationcsv
