### ISSUE TITLE
As an API user, I want to get a key-value-pair JSON response

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#134]
## 💪 Motivation
...so that I can query for a specific subset of fields from the result set.

## 📖 Additional Details

Tightly-coupled in functionality with #120 

## ⚖️ Acceptance Criteria
**Given** a registry + API installment with 1 or more data sets ingested
**When I perform** a query of the API with response format specified as `application/kvp+json`
**Then I expect** the values for the records from the return set in a valid JSON format where each document returned in the result set has the values "key": "value"

**Comment by jordanpadams** [comment]
@tloubrieu-jpl @al-niessner looks like this is done. do we have an API and registry api service commit to reference?

**Comment by al-niessner** [comment]
Not quite ready NASA-PDS/registry-api-service#102
