### ISSUE TITLE
Define initial set of intra-discipline (product-level) search scope

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#14]
We need to come up with some intra-discipline (e.g. Imaging data) search parameters to include in the API.

Some questions:
* at what scope should we include this?
* should this just be custom query parameters (e.g. filter_name, filter_number, etc. == filter)
* for the parameters, should we define a new schema (e.g. custom/filter or search/filter ?)

**Comment by jordanpadams** [comment]
October Schedule Status ⏳:  On track

**Comment by jordanpadams** [comment]
:calendar: december status: on-track

**Comment by tloubrieu-jpl** [comment]
@jordanpadams can we discuss this ticket at the breakout later today ?

**Comment by jordanpadams** [comment]
:calendar: january status: delayed due lack of resources to coordinate with nodes to make this happen. planned for February API WG discussion.

**Comment by jordanpadams** [comment]
See initial model https://mm.tt/1794840971?t=8p17H9WB46
