### ISSUE TITLE
Merge unnecessary individual repository

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-api#140]
## 💪 Motivation
...so that the developer workflow is more simple.
So that we also prepare for a CICD where microservice will be deployed as docker images.

## 📖 Additional Details

See plan https://docs.google.com/spreadsheets/d/1jTP_21jIW9wLnncdAKZgeIESf5eI4HSHQCAe3mVVG-E/edit#gid=0

Use tomono (https://github.com/hraban/tomono) or equivalent tool to preserve git commit history.

New repositories are:

- [x] registry-api : specification of the registry API (shared by server and client)
- [ ] registry-loader: tools to ingest pds4 labels in the registry (batch)
- [x] registry-loader-cli : bigdata harvest client (kept in different repo since each will produce one docker image)
- [x] registry-loader-crawler: bigdata harvest crawler  (kept in different repo since each will produce one docker image)
- [x] registry-loader-reader: bigdata crawler  (kept in different repo since each will produce one docker image)
- [x] registry: docker-compose, terraform, integration tests and documentation

The repositories client side are not handled in this ticket

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect**

**Comment by jordanpadams** [comment]
@tloubrieu-jpl where are we at with this?

**Comment by jordanpadams** [comment]
@tloubrieu-jpl i believe this has been completed per registry and registry-api repos?

**Comment by tloubrieu-jpl** [comment]
@jordanpadams 

We can consider registry done with docker compose and integration but without the terraform scripts. I can ask @jimmie to do that but we can keep it for later.

The registry-loader does not contains the harvest/registry-mgr and common. I was thinking to postpone that since it is not mandatory for us to work and that can create some hick up in the development workflow that we will not need before the end of the build.

I can create separate tickets for that.

**Comment by tloubrieu-jpl** [comment]
This ticket is closed because what is needed for build 12.1 is done.

We'll keep the remaining task in new tickets:
NASA-PDS/pds-registry-app#258
NASA-PDS/pds-registry-app#259
