### ISSUE TITLE
Remove the x-total-count header from the API specification

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-api#145]
## 💪 Motivation
...it is not implemented to there no point having that.
In addfition, the specification itself is not finalized, see https://github.com/NASA-PDS/pds-api/issues/144

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect**

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

Done. It is on swaggerhub as PDS-API-145 and is a branch of 0.5.0-SNAPSHOT. If I chose the wrong point to branch, then let me know and I will do it again from another starting point.

**Comment by gxtchen** [comment]
@tloubrieu-jpl How and where can I verify it is removed?

**Comment by tloubrieu-jpl** [comment]
Hi @gxtchen the specification is published on https://nasa-pds.github.io/pds-api/specifications.html , you are testing version 1.0.0.

Thanks
