### ISSUE TITLE
Update for */{identifier}/bundles and */{identifier}/collections endpoints documentation

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#146]
## 💡 Description

The endpoints:
* `/products/{identifier}/bundles`
* `/products/{identifier}/collections`
* `/collections/{identifier}/bundles`

need to be updated to explicitly note these are the parent bundle/collection for the applicable product

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

Products and collections do not contain bundles but bundles are parents of both products and collections. If you never want to know about parents, then should /products/{id}/collections also be removed?

**Comment by jordanpadams** [comment]
closing as wontfix. this was a misunderstanding of what the `/products/{id}/collections` actually provides.

updating this to include a revision to the API documentation instead.

**Comment by tloubrieu-jpl** [comment]
Documentation is updated on https://github.com/NASA-PDS/pds-api/blob/main/specs/PDS_APIs-search-1.1.0-SNAPSHOT-swagger.yaml
