### ISSUE TITLE
Update fields parameter definition to note that it does not apply to pds4+json and pds4+xml response formats

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#151]
## 💡 Description

Since these formats do not support searching by explicit properties, this does not make any sense? What do these properties represent?

**Comment by jordanpadams** [comment]
@tloubrieu-jpl any thoughts?

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

Do you mean in the summary? You are suggesting having a different summary for PDS4 than all other output types just because it gives you redundant information? In other words, increased code complexity (maintenance  for aesthetics?

**Comment by jordanpadams** [comment]
@al-niessner valid point. then i think the primary thing here is to make it clear why the fields parameter will not work for those response formats. can we instead just update that description?

from:
> returned fields, syntax field0,field1

to:
> Specify the fields to return in the response. Example: fields=field0,field1 . Not applicable to application/pds4+json and application/pds4+xml response formats. 

thoughts?

**Comment by jordanpadams** [comment]
@al-niessner copy that. anything will help for now. and agreed on the overall scrub. In this case I am just trying to hope to avoid something that is blatantly misleading, like this won't work. Vague and minimally helpful is at least a little better?

**Comment by tloubrieu-jpl** [comment]
@al-niessner @jordanpadams I am good no code changes and a clear statement in the swagger documentation saying that`fields` parameter does no impact the response formats 'pds4+json' and 'pds4+xml'.

**Comment by al-niessner** [comment]
@tloubrieu-jpl @jordanpadams 

Which swaggerhub version do you want me to edit then copy to registry-api repo when done?

**Comment by tloubrieu-jpl** [comment]
@al-niessner you can use 0.5.0-SNAPSHOT, that should be the latest version ?
If not you can pull the latest json from registry-api and push manually in swaggerhub.

Note that the reference copy of the specification is supposed to be in the repository pds-api eventually but the mechanism to synchronize it are not there yet.

**Comment by al-niessner** [comment]
@tloubrieu-jpl @jordanpadams 

Process question: If it has been merged, then should this issue still be open?
