### ISSUE TITLE
Check for typos in OpenAPI spec

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#161]
## 💡 Description

Per API WG meeting, noticed some typos in the spec, e.g. producs -> products

**Comment by jordanpadams** [comment]
@tloubrieu-jpl I can make these updates. if I update in SwaggerHub to I sync from there to here? or should I just update here and push back there?

**Comment by tloubrieu-jpl** [comment]
@jordanpadams yes that will be a good test of the procedure.

You can open the psecification on swagger hub using version 1.0.0-SNAPSHOT, then pull -> edit --> save --> push

That should work. However I have not been able this morning to generate the documentation with roundup, I had to update the gh-pages manually.

**Comment by tloubrieu-jpl** [comment]
Closed per PR https://github.com/NASA-PDS/registry-api/pull/120
