### ISSUE TITLE
As a user, I want to have a PDS Search API user guide

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-api#169]
## 💪 Motivation
...so that I know where to start with it and be able to reach all the resources in an organized way and be able to reach every detailed on the API.

## 📖 Additional Details

See chart there https://lucid.app/lucidchart/a27b282a-d7a4-43b3-a324-cef67217c4a1/edit?invitationId=inv_09fc6350-8296-4beb-a205-061f7eb858fb

## ⚖️ Acceptance Criteria
Inspection of new web portal that is user friendly and is an all-inclusive guide to PDS Registry Search API documentation.

**Comment by jordanpadams** [comment]
ready for review at breakout

**Comment by tloubrieu-jpl** [comment]
The documentation is online at https://nasa-pds.github.io/pds-api/
