### ISSUE TITLE
Replace summary-only=true by limit=0

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-api#173]
## 💪 Motivation
...so that we don't have this extra parameter. This is also consistent with elasticSearch or solr API behavior for example.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl so if I understand this update, we just want to remove the summary-only parameter?

**Comment by al-niessner** [comment]
Done with PR NASA-PDS/registry-api#166

**Comment by jordanpadams** [comment]
Reverting per issues identified with #179 and difficulty in making it work for all interfaces

**Comment by jimmie** [comment]
Worked out a way to do this across the board w/ limit=0. Not the best solution, but it works for now.

**Comment by jimmie** [comment]
PR approved and merged
