### ISSUE TITLE
Present ops:Tracking_Meta as a dictionary (instead of list currently)

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-api#174]
## 💪 Motivation
...so that the user does not need to request the list with [0] anytime he need to access the data.

The list does not have a purpose for tracking metadata.

## 📖 Additional Details

Request `curl --location --request GET 'http://localhost:8081/products/urn:nasa:pds:insight_rad::2.1' \ --header 'Accept: application/vnd.nasa.pds.pds4+json'`

Returns:
 ```
"ops:Tracking_Meta": [
           {
               "ops:archive_status": "archived"
           }
       ]

```
We want it to return:
```
"ops:Tracking_Meta": 
           {
               "ops:archive_status": "archived"
           }
     

```

## ⚖️ Acceptance Criteria
**Given** an API server
**When I perform** request  `curl --location --request GET 'http://localhost:8081/products/urn:nasa:pds:insight_rad::2.1' \ --header 'Accept: application/vnd.nasa.pds.pds4+json'`
**Then I expect** the response to contain the following piece of json:
```
"ops:Tracking_Meta": 
           {
               "ops:archive_status": "archived"
           }
     

```

## ⚙️ Engineering Details

This impacts the specification in NASA-PDS/api will transfer the ticket there,

**Comment by jordanpadams** [comment]
resolved per https://github.com/NASA-PDS/registry-api/pull/125
