### ISSUE TITLE
As a user, I want to know how to query observational data only

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#175]
## 💪 Motivation
...so that I can query only observational data products from the registry

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect** 

## ⚙️ Engineering Details

This should be a documentation update with a cookbook example for how to query for just observational data

**Comment by tloubrieu-jpl** [comment]
That should be feasible with the version 1.1. I will check that

**Comment by tloubrieu-jpl** [comment]
Updated pds-api cookbook with example, see commit e6bf63109752f58c92745c40f4443541ad31187d

See section https://nasa-pds.github.io/pds-api/guides/search/cookbook.html#search-observational-products-by-target
