### ISSUE TITLE
Refine format conventions defined by the API WG

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#18]

**Comment by tloubrieu-jpl** [comment]
We discussed today in the WG the JSON structure of the response of the API and agreed to have:
- universal attributes at root of the product document
- properties which are pds4 fields (syntax of the pds4 path need to be refined)

In addition after additional discussion with Jordan, we add:
- a metadata structure (containing version, update/creation date and pds4 label)

XML response will be pure pds4 label
