### ISSUE TITLE
Create a cookbook page on the content negotiation for the PDS Search API

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-api#183]
## 💪 Motivation
...so that it is simply explained to a user how to get various response formats from the API

## 📖 Additional Details

Add that page or section in the PDS Search API User guide.

that should be linked from other pages which uses the --header Accept argument in the examples.

## ⚖️ Acceptance Criteria
Inspection of documentation that content negotiation is described sufficiently.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl does [this satisfy this requirement](https://nasa-pds.github.io/pds-api/search-api-user-guide/response_formats.html) or are you lookin for something else?

**Comment by gxtchen** [comment]
@jimmie the link given by Thomas doesn't work, what is the url that points to the cookbook page?

**Comment by jimmie** [comment]
https://nasa-pds.github.io/pds-api/guides/search/response_formats.html
