### ISSUE TITLE
Define default response fields

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#19]

**Comment by tloubrieu-jpl** [comment]
Default fields are named universal or base attributes.

A first list agreed on during API workng group meeting on 11/04/2020 is:
{
  "id": "string",
  "class": "string",
  "title": "string",
  "description": "string",
  "start_date_time": "string",
  "stop_date_time": "string",
  "observing_system_components": [
    {
      "title": "string",
      "ref": "string",
      "type": "string",
      "description": "string"
    }
  ],
  "targets": [
    {
      "title": "string",
      "ref": "string",
      "type": "string",
      "description": "string"
    }
  ],
  "metadata": {
    "creation_date_time": "string",
    "update_date_time": "string",
    "version": "string",
    "label_url": "string"
  },

+ a reference to mission context product (investigation area in the pds4 information model)
