### ISSUE TITLE
As a user, I want to be able to access the Search API Swagger interface from pds.nasa.gov

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#193]
## 💪 Motivation
...so that I can easily access, interact with, and prototype various queries with the API.

## ⚖️ Acceptance Criteria
**Given** a deployed API and TBD URL
**When I perform** access to that TBD URL and perform a test query
**Then I expect** the swagger UI to query the API and get back results, matching what can be done via Curl or other client mechanisms

## ⚙️ Engineering Details

See sub-tasks for details

**Comment by gxtchen** [comment]
@c-suh @jordanpadams where is the Swagger interface for pds.nasa.gov?

**Comment by tloubrieu-jpl** [comment]
@gxtchen the latest version of the registry-api is meant to fix the issues which prevented us from having the swagger-ui on pds.NASA.gov. These issues were:
- conformance with the NASA web skin
- ability to work properly being a reverse proxy or AWS cloud front.

For you to test that I need to deploy on en-delta or en-gamme.

**Comment by tloubrieu-jpl** [comment]
Hi @gxtchen ,

I deployed the latest registry-api on en-delta, you can get the link here https://pds-en-delta-1955939225.us-west-2.elb.amazonaws.com/ from which you can test the swagger-ui.

**Comment by tloubrieu-jpl** [comment]
However I am thinking now it does not fully test the swagger-ui as intended since the application is not behing Cloud front with a specifci url context (e.g. /api/search/1/... ). I would need to deploy on gamma as well.
