### ISSUE TITLE
Swagger API page does not show the expected deployed API version

### ISSUE THREAD

**Issue by viviant100** [NASA-PDS/pds-api#196]
## 🐛 Describe the bug identified during I&T
 
[Dev API swagger page](https://pds-dev.jpl.nasa.gov/expo/swagger-ui.html) has the latest development version deployment.   In this case, the deployed version is[ v1.0.2](https://github.com/NASA-PDS/registry-api/releases/tag/v1.0.2-SNAPSHOT), but 0.0.1 was shown on the page.  The version shown on the page is inconsistent with its deployed version.  

## 🔁 : Related issues
[pds-api # 51](https://github.com/nasa-pds/pds-api/issues/51)

---

### 📜 To Reproduce
1. Go to 'https://pds-dev.jpl.nasa.gov/expo/swagger-ui.html'
2. Scroll down to the bottom
4. See "API VERSION:0.0.1"

###  🏞Screenshots

![Screen Shot 2022-06-14 at 8 45 38 AM](https://user-images.githubusercontent.com/22924433/173622559-c61ca0b1-681d-48fe-82f9-3cf3a381e701.png)

### 🖥 System Info
 - OS: 11.6.6
 - Browser: Chrome
 - Version 102.0.5005.115

---

**Comment by tloubrieu-jpl** [comment]
Similar bug as also been raised in https://github.com/NASA-PDS/registry-api/issues/149
Not sure if it is a duplicate though because it is not the same version of swagger-ui.
