### ISSUE TITLE
As a user, I want to get TBD response when results are not found.

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-api#198]
## 💪 Motivation
...so that I know what to expect from the API

## 📖 Additional Details

When no results are found, sometimes we get empty response data = [] and sometimes we get 404 error (not found).

We need to clarify that in the specification and implement is accordingly.

Consider the related issue https://github.com/nasa-pds/pds-api/issues/173  which would have to be implemented after the current is done.

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect** 

## ⚙️ Engineering Details

- [ ] TODO - update story to match the decision on the requirement

**Comment by al-niessner** [comment]
@jimmie @jordanpadams @tloubrieu-jpl 

data=[] is when there are no results like "q=lid eq fred" while 404 is when the lid does not exist like /products/fred. In the latter case we can tell that there is no lid/lidvid fred but in the general q=lid eq fred it is simply a query that returned no results like q=vid gt 100000 or q=title like "mary had a little lamb". In all the query cases we know only that no results were found not why like not a real title, vid too large, or bad lid. In the case of /products/{id} we can make the not a valid lid/lidvid assessment and return the 404.

**Comment by al-niessner** [comment]
@jimmie @jordanpadams @tloubrieu-jpl 

Docs in this repository or some other docs? Sorry, but not sure how to translate "the" in "the documentation".

**Comment by jordanpadams** [comment]
@al-niessner excellent point. maybe somewhere under [here](https://github.com/NASA-PDS/pds-api/blob/main/docs/source/guides/search/endpoints.rst)? 

which winds up being published [here](https://nasa-pds.github.io/pds-api/guides/search/endpoints.html)

looking at that page though, it looks outdated. @jimmie may be working on documentation updates as we speak?

**Comment by al-niessner** [comment]
@jimmie @jordanpadams @tloubrieu-jpl 

Most of the documentation in docs/source is about inputs and what we expect. Maybe a section on our output would be appropriate to describe all the errors and their causes.

**Comment by jimmie** [comment]
@jordanpadams - I see the updated version (i.e. 1.1) in place. Did I miss something that is still out of date?

**Comment by jordanpadams** [comment]
@jimmie nevermind, actually this looks good. we will eventually want to expand the area that discusses "Product Classes" but that is OK for now.

**Comment by jordanpadams** [comment]
> @jimmie @jordanpadams @tloubrieu-jpl
> 
> Most of the documentation in docs/source is about inputs and what we expect. Maybe a section on our output would be appropriate to describe all the errors and their causes.
> 
> Maybe a response.rst to go with response_formats.rst?

@al-niessner this sounds great!

**Comment by jordanpadams** [comment]
@al-niessner response.rst actually seems like response formats should be a sub-section within a more generic "Response" page.

**Comment by tloubrieu-jpl** [comment]
Doc has been updated in PR https://github.com/NASA-PDS/pds-api/pull/233

**Comment by miguelp1986** [comment]
Test results: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/4212025
