### ISSUE TITLE
`hits` appears to be showing the current page count, not the overall number of its

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#199]
## 🐛 Describe the bug

Hits is returning `10000` when there are more than 10000 records in the Registry. Per https://opensearch.org/docs/latest/opensearch/ux/#paginate-results, it looks like we are grabbing this number from the `size` field returned from OpenSearch, vs. the `_count`.

## 📜 To Reproduce
1. Go to https://pds.nasa.gov/api/search/1.0/products
2. See:
```json
{
  "summary" : {
    "q" : "",
    "hits" : 10000, <<<<<< not correct
    "took" : 846,
    "start" : 0,
    "limit" : 100,
    "sort" : [ ],
```

**Comment by al-niessner** [comment]
That is the window limitation. It is fixed with NASA-PDS/registry-mgr#53

**Comment by gxtchen** [comment]
How is this fixed? It always returns 10000. I also followed the links in https://github.com/NASA-PDS/registry-mgr/issues/53
The hits are also 10000.

**Comment by al-niessner** [comment]
@gxtchen @jordanpadams @jimmie @tloubrieu-jpl 

The 10000 makes me think you are on a node that is running with the opensearch default configuration which limits the total number of hits it can find to 10000 -- not exactly true but piratically true. Changing the opensearch configuration will fix it but if the configuration has already changed then this is a new item.

**Comment by jordanpadams** [comment]
@gxtchen where are you seeing this issue? in operations?

**Comment by jordanpadams** [comment]
@alexdunnjpl are we still seeing this in ops?

**Comment by jordanpadams** [comment]
@alexdunnjpl 👍 sounds like this is a local testing issue
