### ISSUE TITLE
PDS API documentation needs to be scrubbed

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-api#203]
## 💡 Description

- [x] curl command, url need to be encoded
- [x] need link from nasa-pds.github.io
- [x] remove --location option in curl
- [x] add explanation of curl
- [x] URl or URI instead of URL typo
- [x] scrub this page specifically: https://nasa-pds.github.io/pds-api/search-api-user-guide/endpoints.html 
   - [x] all examples do not work
- [ ]  have I&T test all new code blocks in documentation (@viviant100)
- [x] add information about `ops` keywords
- [x] tag new update of documentation and push online
- [x] #206

## Acceptance criteria:

- the documentation should be reviewed and any unclear sentence or typo should be reported
- all code blocks should be tested and error must be reported

**Comment by tloubrieu-jpl** [comment]
I propose to write the curl command as follow (example):

    % curl -X GET -G http://localhost:8080/gid/product --data-urlencode 'limit=100' --data-urlencode 'fields=title' --data-urlencode 'q=pds:Identification_Area.pds:title ne "InSight HP3 Radiometer Experiment Derived Product:hp3_rad_der_00014_20181211_073"'

**Comment by jordanpadams** [comment]
added #206 to checklist

**Comment by tloubrieu-jpl** [comment]
I don't see the error in the branch, that might have been corrected.

**Comment by tloubrieu-jpl** [comment]
@gxtchen this need to be tested in the deployed documentation https://nasa-pds.github.io/pds-api/
