### ISSUE TITLE
wildcards do not work as expected for all fields

### ISSUE THREAD

**Issue by plawton-umd** [NASA-PDS/pds-api#210]
## 🐛 Describe the bug

Working from https://nasa-pds.github.io/pds-api/guides/search/endpoints.html
The wildcard, specifically "*", behaves inconsistently.  It works for title and description.
For examples

curl --get 'https://pds.nasa.gov/api/search-sbnumd/1.0/collections' --data-urlencode "summary-only=true" --data-urlencode 'q=(title eq "*Tempel*")' 

and

curl --get 'https://pds.nasa.gov/api/search-sbnumd/1.0/collections' --data-urlencode "summary-only=true" --data-urlencode 'q=(description eq "*Tempel*")' 

It does not work for many other field tried - for example name and target.  

## 📜 To Reproduce

curl --get 'https://pds.nasa.gov/api/search-sbnumd/1.0/collections' --data-urlencode "summary-only=true" --data-urlencode 'q=(name eq "*Tempel*")' | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   109    0   109    0     0   1079      0 --:--:-- --:--:-- --:--:--  1079
{
   "summary" : {
      "hits" : 0,
      "limit" : 100,
      "properties" : [],
      "q" : "(name eq \"*Tempel*\")",
      "sort" : [],
      "start" : 0,
      "took" : 20
   }
}

Note the 0 hits.

## 🕵️ Expected behavior

Expect a result similar to that of title and description.

{
   "summary" : {
      "hits" : 6,
      "limit" : 100,
      "properties" : [
         "_package_id",
         "description",
         "lid",
...
      ],
      "q" : "(description eq \"*Tempel*\")",
      "sort" : [],
      "start" : 0,
      "took" : 318
   }
}

Note 6 hits.

## 📚 Version of Software Used

curl --get 'https://pds.nasa.gov/api/search-sbnumd/1.0/

## 🖥 System Info
 - OS: Mac 11.4
 - Browser n/a (terminal window)
 - Version n/a
- curl 7.64.1 (x86_64-apple-darwin20.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0
Release-Date: 2019-03-27

---

**Comment by jordanpadams** [comment]
@plawton-umd this is probably the OpenSearch types we are using to ingest and tokenize the data. will research this further.

**Comment by al-niessner** [comment]
@jordanpadams what needs done to this ticket? You mentioned about that it already fixed and documentation is waiting to be updated.

**Comment by jordanpadams** [comment]
@al-niessner fixing the documentation would be needed here

**Comment by al-niessner** [comment]
@jordanpadams @jimmie - where is the documentation that needs fixed as I have never seen it but only discussed it in the abstract?

**Comment by jordanpadams** [comment]
@al-niessner https://github.com/NASA-PDS/pds-api/tree/main/docs/source/guides/search
