### ISSUE TITLE
vnd.nasa.pds.pds4+xml format does not return information

### ISSUE THREAD

**Issue by plawton-umd** [NASA-PDS/pds-api#215]
## 🐛 Describe the bug

Using the format information on https://nasa-pds.github.io/pds-api/guides/search/response_formats.html

curl --get 'https://pds.nasa.gov/api/search-sbnumd/1.0/bundles/urn:nasa:pds:gbo-kpno::4.0/collections' --header 'Accept: application/vnd.nasa.pds.pds4+xml'

returns nothing.

## 📜 To Reproduce

type

curl --get 'https://pds.nasa.gov/api/search-sbnumd/1.0/bundles/urn:nasa:pds:gbo-kpno::4.0/collections' --header 'Accept: application/vnd.nasa.pds.pds4+xml'

## 🕵️ Expected behavior

Return of the information that the command line

curl --get 'https://pds.nasa.gov/api/search-sbnumd/1.0/bundles/urn:nasa:pds:gbo-kpno::4.0/collections' --header 'Accept: application/xml'

returns with the expected differences.

## 📚 Version of Software Used

1.0

## 🩺 Test Data / Additional context

see above

## 🖥 System Info

MacOS 11.4
terminal window

---

## 🦄 Related requirements
* 🦄 NASA-PDS/registry-api#440

**Comment by jordanpadams** [comment]
@jimmie can you verify if this is still a problem with the latest version of the registry (probably using @al-niessner's current branch on registry-api)

**Comment by jordanpadams** [comment]
@jimmie actually, let's move this down in priority a notch for the moment. can we try to get those open cloud-task tickets for multi-tenancy, web analytics, and deploying registries in NGAP wrapped up with our remaining time in this sprint / build?

**Comment by jordanpadams** [comment]
@viviant100 same goes for this issue associated with this requirement:

* #125

**Comment by viviant100** [comment]
Noted. I&T ticket [#29](https://github.com/NASA-PDS/system-i-n-t/issues/29) is created to track this requirement.

**Comment by miguelp1986** [comment]
Test results: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/4212166

**Comment by jordanpadams** [comment]
@tloubrieu-jpl can correct me if I am wrong, but I believe this is fixed but not yet deployed. That should be included in our deployment coming in a few weeks.

**Comment by msbentley** [comment]
Hi @jordanpadams should this now work? Or am I suffering user error again? ;-)

**Comment by tloubrieu-jpl** [comment]
Hi @msbentley , although the fix has been developed it is not available in production yet since we did not tag a new release with the fix.
That should happen in a few weeks from now.

Sorry about that.

**Comment by msbentley** [comment]
Thanks @tloubrieu-jpl
