### ISSUE TITLE
Past versions are being returned by API, by default

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#220]
## 🐛 Describe the bug

Per https://github.com/NASA-PDS/pds-api/issues/96, the API should only include the latest versions of products in search results.

## 📜 To Reproduce

```
curl -X 'GET' \
  'https://pds.nasa.gov/api/search/1.0/products?fields=lidvid&limit=100&q=lid%20eq%20%22urn%3Anasa%3Apds%3Amaven.spice%22&start=0&summary-only=false' \
  -H 'accept: application/csv'
```

Current API functionality is finding all products with a specific lid then returns all lidvids with that lid. If you had done `/products/urn:nasa:pds:maven.spice` then you would have just the latest. It is the q= that does not allow latest/all processing.

---

## 🦄 Related requirements
🦄 #96
🦄 #221

**Comment by al-niessner** [comment]
See #221 its duplicate and where the comment are

**Comment by jordanpadams** [comment]
implementation complete. deployment is being tracked here:

https://github.com/NASA-PDS/registry/issues/140
https://github.com/NASA-PDS/registry/issues/141
