### ISSUE TITLE
Make the registry-api use the new latest index

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-api#236]
## 💡 Description

This task aims at fulfilling requirement #221 and correcting bug #220

**Comment by alexdunnjpl** [comment]
@tloubrieu-jpl if this is an urgent item (I see a one-week-deadline) and a trivial fix (seems like, if it's just switching from one index to another), it might be worth handballing it on to someone who already has a development/testing flow set up for registry-api - I'm still trying to figure out a good way to swap dev versions of individual components in/out of a development instance of registry.

**Comment by tloubrieu-jpl** [comment]
Hi @alexdunnjpl this is not urgent, it is for next sprint which starts tomorrow, and actually we might revise our plan on that, so no hurry.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl correct me if I am wrong, but we ditched this concept per https://github.com/NASA-PDS/registry-api/pull/193#event-8041983384

**Comment by tloubrieu-jpl** [comment]
Yes, thanks @jordanpadams
