### ISSUE TITLE
As a user, I want to get application/json response format by default if I request an API url in my browser

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-api#239]
## 💪 Motivation
...so that I can see well defined json and that possibly my browser plugin help me to explore it.

## 📖 Additional Details

A plugin which should work on the API response is https://github.com/callumlocke/json-formatter

## ⚖️ Acceptance Criteria
**Given** an API request
**When I perform** it in a web browser (Google Chrome, Firefox, Safari)
**Then I expect** to get a parsable JSON, which is understood by plugin https://github.com/callumlocke/json-formatter for example

## ⚙️ Engineering Details

In my Google Chrome browser on macos the request comes with Accept header value "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"

I guess we should make the API return application/json when such Accept header is received. Maybe we should identify application/json as text/html.

**Comment by tloubrieu-jpl** [comment]
I made it part of the swagger EPIC not to loose this minor ticket.

**Comment by tloubrieu-jpl** [comment]
Hi @alexdunnjpl , I stole this ticket from you...

**Comment by alexdunnjpl** [comment]
All yours!
