### ISSUE TITLE
PDS-API returns Error 500 for classes/collections 

### ISSUE THREAD

**Issue by gxtchen** [NASA-PDS/pds-api#245]
## 🐛 Describe the bug identified during I&T
PDS-API works when querying for products and bundles, but returns error code 500 when querying for collections.

### 📜 To Reproduce
1. Go to https://pds.nasa.gov/api/search/1.1/classes/collections
2. using curl 
% curl --get 'https://pds.nasa.gov/api/search/1.1/classes/collections' \
--data-urlencode 'limit=10' \
--data-urlencode 'q=(pds:Primary_Result_Summary.pds:processing_level eq "Raw")'
3. See error
{"timestamp":1672733821256,"status":500,"error":"Internal Server Error","path":"/classes/collections"}%    
or see this on the browser:
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Tue Jan 03 08:10:45 UTC 2023
There was an unexpected error (type=Internal Server Error, status=500).

### 🕵️ Expected behavior
should return results in json.

**Comment by jordanpadams** [comment]
@gxtchen can you try to deploy this locally and see if this still fails? It is my understanding this has been fixed. We are just working on a new deployment
