### ISSUE TITLE
link to registry-api documentation from registry page is incorrect

### ISSUE THREAD

**Issue by jimmie** [NASA-PDS/pds-api#251]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

On the page: https://nasa-pds.github.io/registry/cloud_startup.html#registry-api there is a link intended to point to the registry api documentation in this sentence:

_

> Once data has been ingested using the Registry Tools, queries can be submitted using the Registry API which is [documented here](https://nasa-pds.github.io/pds-api/search-api-user-guide.html).

_

The link is incorrect, instead it should point to: https://nasa-pds.github.io/pds-api/guides/search.html

### 🕵️ Expected behavior

The link to send the user to the search documentation.

### 📜 To Reproduce

```bash
Click on the link indicated above.
```

### 🖥 Environment Info

```bash
n/a
```

**Comment by tloubrieu-jpl** [comment]
At @jimmie I started that my mistake, thinking it was on my board. So I re-assigned that ticket to me and will finalize that in a minute. Thanks

**Comment by tloubrieu-jpl** [comment]
The fix has been done in commit b5730bee89fc0099cfe3947505c8c3ff21d99895 and published on page  https://nasa-pds.github.io/registry/cloud_startup.html#registry-api
