### ISSUE TITLE
API search returns 500 for anything besides simple queries

### ISSUE THREAD

**Issue by msbentley** [NASA-PDS/pds-api#259]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

Query string:
```
q='geom:Distances_Specific.geom:spacecraft_heliocentric_distance gt 160000000'
```
works fine, as does
```
q='geom:Distances_Specific.geom:spacecraft_heliocentric_distance lt 180000000'
```
however, this gives a 500 error:
```
q='geom:Distances_Specific.geom:spacecraft_heliocentric_distance gt 160000000 and geom:Distances_Specific.geom:spacecraft_heliocentric_distance lt 180000000'
```
I have tried adding brackets etc. but nothing seems to help here. I have tried queries also with or instead of and, substituting ge and le intsead of gt and lt but nothing seems to work.

### 🕵️ Expected behavior

I expected this search to succeed and yield results.

### 📜 To Reproduce

1. Search as above. In my case I was using python/requests:
```python
r = requests.get(pds_url + 'products',
    params={
        'limit': 10,
        'fields': 'geom:Distances_Specific.geom:spacecraft_heliocentric_distance',
        'q': 'geom:Distances_Specific.geom:spacecraft_heliocentric_distance gt 160000000 and geom:Distances_Specific.geom:spacecraft_heliocentric_distance lt 180000000'})
```
but I have also tried with various other tools.

### 🦄 Related requirements

🦄 #xyz

**Comment by jordanpadams** [comment]
@tloubrieu-jpl @alexdunnjpl can you verify this is fixed with the new version of the API coming out?

**Comment by alexdunnjpl** [comment]
@jordanpadams @msbentley do we have a known-broken version to ensure I can compare behaviour properly?

**Comment by msbentley** [comment]
From my side I was testing with the live PDS endpoint (https://pds.nasa.gov/api/search/1/)

**Comment by tloubrieu-jpl** [comment]
@msbentley I will look at your tests, but if that is quick on your side, you can replace your current endpoint with https://pds.nasa.gov/api/search-en-gamma/1/ where the latest stable version of the API service is deployed in beta.

**Comment by tloubrieu-jpl** [comment]
Hi @msbentley , actually the q parsing is quite rigorous on the usage of brackets. There are needed everywhere you can think they can help (as in java, unlike python).
The q value which works in your case is:
    ((geom:Distances_Specific.geom:spacecraft_heliocentric_distance gt 160000000) and (geom:Distances_Specific.geom:spacecraft_heliocentric_distance lt 180000000))

We made that syntax choice to simplify the query parser which was developed to handle these complex queries. I will try to make the documentation more clear on that.

**Comment by alexdunnjpl** [comment]
@tloubrieu-jpl documentation aside, should I open a ticket to return a HTTP400 with a descriptive message on query parse failure?

**Comment by tloubrieu-jpl** [comment]
Yes @alexdunnjpl that would be nice, I asked for that a while ago but we gave up on that, the ticket is still there https://github.com/NASA-PDS/registry-api/issues/13 so no need to create a new one. You can re-evaluate the analysis which was done then. If feasible we can put that in our priorities again.

**Comment by msbentley** [comment]
Aha, thanks @tloubrieu-jpl - it never would have occured to me to bracket the entire query string, given that a simple query doesn't need this - yes, extensive docs and examples would be great, for those of us who have never had to do battle in java ;-)

**Comment by tloubrieu-jpl** [comment]
@msbentley I created a ticket https://github.com/NASA-PDS/registry-api/issues/327 to see if we can make the parser a bit more lenient with brackets.
