### ISSUE TITLE
PDS API has an undocumented hit limit of 10000 (even when not asking for data)

### ISSUE THREAD

**Issue by msbentley** [NASA-PDS/pds-api#261]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When testing queries in the API, I often want to explore the number of products matching a given query, even without looking into the data themselves. e.g. I run a query with limit=0. Doing this for broad queries I reach a cap of 10000 in summary/hits.

1. I can't obviously find this documented limit in the docs,
2. there are many use cases for counting products which could run into millions.

Given that we already have the limit keyword, I don't understand why "hits" is limited here and would really like to be able to count products into the millions.

### 🕵️ Expected behavior

I expected summar/hits of the response to give the accurate number of results for my query, and not an artificial limit.

### 📜 To Reproduce

```python
r = requests.get(pds_url + 'products',
    params={
        'limit': 0,
        'q': 'pds:Time_Coordinates.pds:start_date_time gt "2001-05-10T00:00:00Z"'})

r.json()['summary']['hits']
```
This returns 10000

### 🦄 Related requirements

🦄 #xyz

**Comment by jordanpadams** [comment]
@jimmie can we make sure all the registries are reconfigured appropriately?

@alexdunnjpl can we make sure the current hit limit is documented somewhere?

**Comment by alexdunnjpl** [comment]
@jordanpadams regarding docs, does this limit exist in current versions?  It shouldn't.

**Comment by tloubrieu-jpl** [comment]
We should not have that limit anymore since this ticket https://github.com/NASA-PDS/registry-api/issues/291 is closed. We will investigate that.
