### ISSUE TITLE
PDS API is not respecting the sort field

### ISSUE THREAD

**Issue by msbentley** [NASA-PDS/pds-api#262]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When including the sort field, the API doesn't seem to return data sorted as expected (there is no change).

### 🕵️ Expected behavior

I expect the API to respect the sort order, or to given error if this is not possible.

### 📜 To Reproduce

```python
r = requests.get(pds_url + 'products',
    params={
        'limit': 10,
         'q': 'pds:Time_Coordinates.pds:start_date_time gt "2023-01-01T00:00:00Z"',
         'fields': 'lid, pds:Time_Coordinates/pds:start_date_time, pds:Time_Coordinates/pds:stop_date_time',
         'sort': 'pds:Time_Coordinates.pds:start_date_time desc'})

pd.DataFrame.from_dict(r.json()['data'])
```
The same data are returned in the same order above whether I include `asc` or `desc` in the sort parameter, or indeed if I choose another field to sort by.

I have also tried with different return types, e.g. CSV, with the same result, e.g. 

![image](https://user-images.githubusercontent.com/1671065/234599899-dda2f658-78c9-4924-af94-893c1ed818cb.png)

### 🦄 Related requirements

🦄 #xyz

**Comment by alexdunnjpl** [comment]
[Corresponding issue in registry-api](https://github.com/NASA-PDS/registry-api/issues/250#issuecomment-1439440053)
