### ISSUE TITLE
Initialize a Wrapper API Client

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-api#274]
## 💡 Description

The wrapper will be a python package running server side and wrapping called to the API through the pds-api-client code automatically generated from the openapi specification.

See some details here: https://docs.google.com/presentation/d/1jlOPAgLy6TauXsPse_JtdRgiU0MLCqMneM3qLfRpl64/edit?usp=sharing

The sub tasks are:
- create the skeleton of the wrapper library
- add methods to implement the OSIRIS REX notebook, test it

**Comment by jordanpadams** [comment]
📆 November status: Library initialized and reviewed with API WG. On schedule. https://github.com/NASA-PDS/updart

**Comment by jordanpadams** [comment]
📆 December status: In work. On schedule

**Comment by jordanpadams** [comment]
📆 01/2024 status: In work. On schedule.

**Comment by jordanpadams** [comment]
📆 02/2024 status: initial library completed.
