### ISSUE TITLE
As a developer, I want a continuous deployment of the API available for testing

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#51]
...so that we can utilize the PDS Client and test the API at "any time" against some deployed version with some data in it.

aka. CI/CD of the latest API server

## Acceptance Criteria
**Given** I've made a change to the source code of the PDS API Service (ignoring docs)
**When I perform** a commit in Github
**Then I expect** to trigger a build and deployment to pds-gamma (and/or AWS if that is also reasonable)

**Comment by tloubrieu-jpl** [comment]
pds-dev is going to be the reverse proxy for the services set up to pds-expo.

For registry api that would be TBC (@tloubrieu-jpl)

**Comment by tloubrieu-jpl** [comment]
- the docker images will be updated and published as part of the github action
- the jenkins deployment will be re-made every nigth.

**Comment by nutjob4life** [comment]
See NASA-PDS/devops#23 for the GitHub Action progress

**Comment by nutjob4life** [comment]
This now works from almost any place at JPL, including by developers at home on VPN:
```console
$ curl --silent https://pds-dev.jpl.nasa.gov/expo/products | wc -c
335642
$ echo \U+1F389
🎉
```

**Comment by tloubrieu-jpl** [comment]
We would like that to work as well https://pds-dev.jpl.nasa.gov/swagger-ui.html

**Comment by nutjob4life** [comment]
@tloubrieu-jpl I think we want https://pds-dev.jpl.nasa.gov/expo/ (with `/expo/`).

Does this look better?
![Screen Shot 2022-04-12 at 4.04.35 PM.png](https://images.zenhubusercontent.com/5d52e426b9ebc816204aa77d/b257954b-e5b8-4df1-a6ac-fc1744ff2167)

**Comment by nutjob4life** [comment]
@tloubrieu-jpl quick question, should it be https://pds-dev.jpl.nasa.gov/expo/ or no `/expo/`?

**Comment by nutjob4life** [comment]
@tloubrieu-jpl keep multiple versions of the registry API up and running, not just the latest?

I guess we could, but certainly not in time for the end of sprint 😬 we'd have to develop some kind of a front-end dispatcher, otherwise every version would require sysadmin intervention in order to get the new rewrite/reverse proxy rules in place.

**Comment by tloubrieu-jpl** [comment]
@nutjob4life certainly for now only the latest is needed. Let's keep multiple versions for later if the needs come when we'll have multiple version to maintain because our users do not upgrade. Even in this case that will be ok to ask the sysadmin to create a new proxy rule.

**Comment by tloubrieu-jpl** [comment]
This ticket can be closed since the API is accessible from https://pds-dev.jpl.nasa.gov/expo/ .
The revision of the url to enable multiple serbices to be expose will be done in ticket NASA-PDS/devops#2
