### ISSUE TITLE
Get investigation area/targets/instruments from external ids

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-api#52]
As a user, I want to get a product description as follow, regarding the links to investigation area, target and instruments:
```
{
“investigations”: [ {
“id”: “urn:nasa:pds:context:investigation:mission.orex”,
“href”: “{baseUrl}/products/urn:nasa:pds:context:investigation:mission.orex”
} ],
observing_system_components: {
[
{
“id”: “urn:nasa:pds:context:instrument_host:spacecraft.orex”,
“href”: “{baseUrl}/products/urn:nasa:pds:context:instrument_host:spacecraft.orex”
},
{
“id”: “urn:nasa:pds:context:instrument:ocams.orex”,
“href”: {baseUrl}/products/urn:nasa:pds:context:instrument:ocams.orex”
},
]
},

```
- baseUrl is the url of the API application so that the full value in href can be resolved (e.g. in a web browser)
- the values here are given as examples, they are read from the elasticsearch document, for example:

 "pds:Internal_Reference/pds:lid_reference": [
                        "urn:nasa:pds:context:investigation:mission.messenger",
                        "urn:nasa:pds:context:instrument_host:spacecraft.mess",
                        "urn:nasa:pds:context:instrument:mascs.mess",
                        "urn:nasa:pds:context:instrument:grs.mess",
                        "urn:nasa:pds:context:instrument:ns.mess",
                        "urn:nasa:pds:context:target:planet.mercury"
                    ],
                    "pds:Internal_Reference/pds:reference_type": [
                        "collection_to_investigation",
                        "is_instrument_host",
                        "is_instrument",
                        "is_instrument",
                        "is_instrument",
                        "collection_to_target"
                    ],

**Comment by al-niessner** [comment]
I take it that I need to do the elastic search or are they buried in the [EntityProduct](https://github.com/NASA-PDS/registry-api-service/blob/1b3e87bd6064d4026288f0c07e3ce36202b86294/src/main/java/gov/nasa/pds/api/engineering/elasticsearch/ElasticSearchUtil.java#L52)

**Comment by al-niessner** [comment]
It seems that this [block](https://github.com/NASA-PDS/registry-api-service/blob/1b3e87bd6064d4026288f0c07e3ce36202b86294/src/main/java/gov/nasa/pds/api/engineering/elasticsearch/entities/EntityProduct.java#L74-L91) needs to be commented out (along with some get/set stuff as well) to retrieve the information needed for creating the href later. Am I way off base or is that about it?

**Comment by tloubrieu-jpl** [comment]
Actually yes, the code used to be able to pull this information from the elasticsearch object so you will be able to uncomment stuff to make that work.

The issue I had was that i was pulling the name, type from elasticsearch as well and not only the info is not reliable but the structure is not appropriate, so while you uncomment stuff, you need to only pull the id and type and not populate the name/type/description info in the API output.

**Comment by al-niessner** [comment]
Am I using old software somewhere? When I query elastic search, the JSON objects it returns does not contain Internal_Reference (from your original post) at all anywhere. However there are these 3 items that would make it much simpler:

```
"ref_lid_instrument":["urn:nasa:pds:context:instrument:grs.mess",
                                 "urn:nasa:pds:context:instrument:mascs.mess",
                                 "urn:nasa:pds:context:instrument:ns.mess"]
"ref_lid_investigation":"urn:nasa:pds:context:investigation:mission.messenger"
"ref_lid_target":"urn:nasa:pds:context:target:planet.mercury"
```

However, these are not all arrays like what the Java is expecting. If the JSON snippet above in this comment is correct, then I can adjust the Java to match and make it all work. If the snippet is wrong, then what new version of pds-registry-api and/or other software do I need?
