### ISSUE TITLE
As an API user, I want to know the Product(s) that belong to a given Bundle.

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#59]
For more information on how to populate this new feature request, see the PDS Wiki on User Story Development:

https://github.com/NASA-PDS/nasa-pds.github.io/wiki/Issue-Tracking#user-story-development

## Motivation
...so that I can <why do you want to do this?>

## Additional Details
Notional API Design:
```
GET /bundles/{lidvid}/products
```

See https://github.com/NASA-PDS/pds-registry-app/issues/144 and https://github.com/NASA-PDS/pds-registry-app/issues/143 for how the registry ingests primary and secondary products.

Note: The logic here is a little funky:
1. find all primary and secondary collections for the bundle
2. find all primary and secondary products for those collections
    a. if product comes from secondary collection, ALL products from those collections should be considered secondary

## Acceptance Criteria
**Given** I have a bundle LID OR LIDVID
**When I perform** an API query by that LIDVID for its products
**Then I expect** the API to return the primary product(s) AND any secondary product(s) for that bundle

## Sub-tasks
- [ ] Update Swagger API
- [ ] Implement in API Server

**Comment by tloubrieu-jpl** [comment]
Validated in pull request: https://github.com/NASA-PDS/registry-api-service/pull/29
