### ISSUE TITLE
As an API user, I want to get only the fields I explicitly requested

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-api#65]
## Motivation
...so that I can I only get the properties and nothing else. If I am querying for something specific, then I know what I want and don't want extra default properties.

## Additional Details
As a PDS knowledgeable user, I want an extra API end-point which does not contains default attributes that will impact the performance of my request.
As a newbie user I still want to have a default representation of the PDS products in a simple intuitive format.

## Acceptance Criteria
**Given** PDS4 fields 2 fields
**When I perform** an API request
**Then I expect** I want to get this 2 fields only
**And I expect** for each product returned, at least one of the 2 fields has a valid value

## Engineering Details
This can be done by implementing an extra end-point

/<prod type>/properties 
(where <prod type> is products, collections or bundles)

where parameters:
q,fields,start,limit would apply. 

This end-point would only return the content of the current properties object in the current json response from  /<prod type>

The end-point could also be created
/<prod type>/<lidvid>/properties

it would only take 'fields' as a parameter.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl where possible, try to use the [Feature Request issue template](https://github.com/NASA-PDS/pds-api/issues/new?assignees=jordanpadams&labels=requirement%2C+needs%3Atriage&template=feature_request.md&title=As+a+%3Cwhat+is+the+user%27s+role%3F%3E+I+want+to+%3Cwhat+is+the+user+trying+to+accomplish%3F%3E) when creating a new issue in order to stick to the User Story template we have laid out. It will also put it in my "inbox" to triage and and we can discuss priority.

note: unfortunately it looks like Zenhub doesn't really pick up these issue templates at the moment. will look into that and/or file a bug report.

**Comment by tloubrieu-jpl** [comment]
Ooops, I'll be more careful next time. I would not be surprise if I just had removed the default template and wrote whatever I had in mind.

**Comment by jordanpadams** [comment]
> Ooops, I'll be more careful next time. I would not be surprise if I just had removed the default template and wrote whatever I had in mind.

No worries. Even if we only fill out part of it, there is a slim chance someone will go back and fill it out :-)

**Comment by jordanpadams** [comment]
@tloubrieu-jpl per this note:

> As a PDS knowledgeable user, I want an extra API end-point which does not contains default attributes that will impact the performance of my request.

should this be an API end-point? or just a parameter you can set to ignore that extra metadata?

**Comment by tloubrieu-jpl** [comment]
@jordanpadams I liked the idea to use an end point with /properties in the end, for example /product/properties to show that the we are strictly get the content of properties from this end point compared to /products which send back the full product structure:
{
 id
 title
...
observation_systems
...
properties {}
}

This sounded intuitive to me since properties is a component for the full object, and the user would not be surprise by the change of the structure of the responses for the same end-point. But as you said, we could also do it with a url parameter, we could even do both new end-point and parameter actually.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams actually, this will be a bit more complicated than I though to use the same end-point. This reason is in the swagger/openapi definition of the API one model is attached to each end-point. So we would need either to have a model which definition covers both the full object specification and only the content of properties (their structure is completely different) or find a way to have 2 models for a single end-points.
The spingboot application is based on the swagger definition of the API so this is a constraint we have with the current solution.  I can look further into that if it is critical.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl but as a user, should I have to care?

**Comment by jordanpadams** [comment]
what if we put that general information (e.g observation_systems, targets) under some other generic object separate from properties? or maybe even under properties?
