### ISSUE TITLE
As an API user, I want to get an XML response

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-api#66]
## Motivation

...so that the API can support numerous format responses to support the community.

## Details

**Note: The content should match the application/json structure**

That can be done easily by applying the default springboot content negotiation instead of the custom made content negotiation which returns the original pds4 label.

The pds4 label response could be kept for content-type=application/pds4+xml

## Acceptance criteria

**Given** any API request
**When I perform** with content-type header 'application/xml'
**I expect to** get the same attributes and same structure as the same request run with content-type header set to `application/json`

**Comment by tloubrieu-jpl** [comment]
We are still having an issue with xml not serializing the list values in the properties dictionnary.

**Comment by gxtchen** [comment]
@viviant100 @tloubrieu-jpl Hi Thomas, I don't see the changes in jpl-gamma, is the fix in pds-registry-app-1.0.3?

**Comment by tloubrieu-jpl** [comment]
Hi @gxtchen ,

Now this component is hosted in the repository https://github.com/NASA-PDS/registry-api . Sorry I missed to tell you that.
The continuous integration/continuous delivery is not working yet on this repository so you don't have a snashot release to test with. I will fix that today hopefully.

**Comment by tloubrieu-jpl** [comment]
Hi @gxtchen ,

I updated the registry-api repository so that you have a released package to test with.

See the instructions in the main README on https://github.com/NASA-PDS/registry-api

Let me know if you have questions.

Thanks

**Comment by gxtchen** [comment]
@tloubrieu-jpl after running docker compose --profile=dev-api up command, all processes exited except for docker-elasticsearch-1. I can't load the api then.

**Comment by gxtchen** [comment]
@viviant100 @tloubrieu-jpl 
Doesn't seems to work.
When I tried to get application/json 
I got curl -X GET --header 'Accept: application/json' 'http://localhost:8080/collections?limit=100&keyword=*&only-summary=false'
and return code of 200 with 3 hits.
next, I tried application/json
curl -X GET --header 'Accept: application/json' 'http://localhost:8080/collections?limit=100&keyword=*&only-summary=false'
It also works.
But when I tried application/xml
I got this in the Curl stirng
curl -X GET --header 'Accept: application/json' 'http://localhost:8080/collections?limit=100&keyword=*&only-summary=false'
and I got a return code of 501
and no content.
