### ISSUE TITLE
As an API user, I want to search by a temporal range as an ISO-8601 time interval.

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#72]
## Motivation
...so that I can find data within some notional time.

## Additional Details

The API enables this out of the box. This issue is really just to document how to do it.

For example: https://cmr.earthdata.nasa.gov/search/site/docs/search/api.html#temporal-range-searches

Should we enable "fuzzy" temporal ranges (e.g. datetime ge 2017)? or maybe that is a separate ticket and we wait to see if people are actually upset about requiring  ISO 8601 time intervals.

## Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect** 

## Engineering Details

Should require  ISO-8601 time intervals.

**Comment by tdddblog** [comment]
Boolean operators and parenthesis are broken in current query lexer / parser implementation, therefore range queries which require `AND` operator do not work.
I had to fix lexer (https://github.com/NASA-PDS/api-search-query-lexer/pull/6) and API Service (https://github.com/NASA-PDS/registry-api-service/pull/72) projects.

**Comment by jordanpadams** [comment]
will revert https://github.com/NASA-PDS/api-search-query-lexer/pull/6 and update https://github.com/NASA-PDS/registry-api-service/pull/72 to use the changes we will introduce to use the `like` wildcard query.
