### ISSUE TITLE
As an API user, I want to search using URL parameters

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#83]
## Motivation
...so that I can provide more simple search criteria, and do not need to know the complexity of the API query syntax

## Acceptance Criteria
**Given** a deployed API with data ingested
**When I perform** a query against an API endpoint with `<endpoint>?lidvid eq *my_lid*`
**Then I expect** the API to query the Registry for a lidvid that matches `*my_lid*`.

**Comment by jordanpadams** [comment]
This was completed at the initiation of the API. See https://pds-gamma.jpl.nasa.gov/api/products?limit=100&q=lid%20eq%20*insight*&only-summary=false as an example

**Comment by gxtchen** [comment]
@jordanpadams Your request string doesn't work for me using firefox or safari.

**Comment by jordanpadams** [comment]
@gxtchen you have to use curl or wget to test this. this will no longer work in the browser because we disabled the HTML / XML responses.

**Comment by tloubrieu-jpl** [comment]
@gxtchen I was able to make that request work:
curl --location --request GET 'http://pds-gamma.jpl.nasa.gov/api/products?q=lid eq "urn:nasa:pds:insight_documents"&limit=100&only-summary=False'

I think this is equivalent to the one which you tested but did not work. I think the reason why it did not work is the quote missing around the lid url value. Did you get this request from a documentation that we should update.
