### ISSUE TITLE
Update Swagger OpenAPI with new `hits` and `took` fields

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#87]

**Comment by al-niessner** [comment]
@tloubrieu-jpl @jordanpadams 

"hits" is very elasticsearch. Do you want hits or total or known_count or number_of_known or something else.

Also, extending this ticket to include adding "took" or "processing_time".

**Comment by jordanpadams** [comment]
Resolved per https://github.com/NASA-PDS/pds-api/commit/7fe91eb0438c90cf93713ad1053418815036136a
