### ISSUE TITLE
As a user,I want to get the list of properties available in summary sorted in alphabetical order

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-api#88]
## Motivation
...so that I can search what I am interested in more efficiently.

## Acceptance Criteria
**Given** 
**When I perform** When I perform a request (e.g. with only-summry=True)
**Then I expect** the summary.properties array to be sorted in alphabetic order

## Engineering Details

Instead of a HashSet object currently used (see for example https://github.com/NASA-PDS/registry-api-service/blob/db52a571ba46c47a9792838e30d0142c692ce83f/src/main/java/gov/nasa/pds/api/engineering/controllers/MyProductsApiBareController.java#L110) one can use an ordered object (Tree...).

**Comment by tloubrieu-jpl** [comment]
@tdddblog I created a ticket for your request on ordering the list of properties in summary. Can you update the type of object you advised to use to handle that ? I missed to take note of that. Thanks.

**Comment by jordanpadams** [comment]
Lowering priority of this task and de-scoping from B12.1

**Comment by jordanpadams** [comment]
closing as duplicate to https://github.com/NASA-PDS/registry-api/issues/506
