### ISSUE TITLE
As a user, I want an end-point of each of the PDS4 IM classes of products

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-api#94]
## Motivation
...so that I can easily request only the suclass I am interested in (bundle, collection, observational_products, document, context). 

This ticket is needed to implement the Search UI, see https://github.com/nasa-pds/pds.nasa.gov-search/issues/33

## Additional Details

We will still have a generic end-point /products which we return any classe of product.

## Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect** 

## Engineering Details

This ticket is linked to https://github.com/NASA-PDS/registry-api-service/issues/34

**Comment by jordanpadams** [comment]
This should be captured by https://github.com/NASA-PDS/pds-api/issues/180

**Comment by jordanpadams** [comment]
closed per #180
