### ISSUE TITLE
As a user, I want to query for all versions of a product

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-api#95]
## Motivation
...so that I can see the provenance history of a particular product

## Acceptance Criteria
**Given** a registry populated with multiple versions of a product
**When I perform** a query to the `products/{lid}` endpoint by LID
**Then I expect** to have the latest version of the product returned, only

**Given** a registry populated with multiple versions of a collection
**When I perform** a query to the `collections/{lid}` endpoint by LID
**Then I expect** to have the latest version of the collection returned, only

**Given** a registry populated with multiple versions of a bundle
**When I perform** a query to the `bundles/{lid}` endpoint by LID
**Then I expect** to have the latest version of the bundle returned, only

## Engineering Details

- [ ] design the API (swagger) for that
- [ ] develop the new feature

**Comment by jordanpadams** [comment]
initial version closed per https://github.com/NASA-PDS/registry-api-service/pull/67
