### ISSUE TITLE
Identify and ingest bundle containing collections and products with multiple versions into dev registry

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#97]
7 bundle versions containing
* 1 or more collections with 5 total versions
* 1 or more products contains 3 total versions

So basically minimum criteria:
bundle_x::1.0
-- collection_y::1.0
---- product_a::1.0

bundle_x::2.0
-- collection_y::1.0
---- product_a::1.0

bundle_x::3.0
-- collection_y::2.0
---- product_a::2.0

bundle_x::4.0
-- collection_y::2.0
---- product_a::2.0

And so on. The irregularity in the number of versions is intentional to avoid mistakes.

Obviously, having more than one collection and several products would be great, but we really just want to make sure we can test out some of the versioning-related requirements via the API.

Maybe just a somewhat shrunk down version of https://naif.jpl.nasa.gov/pub/naif/pds/pds4/maven/maven_spice/spice_kernels/ ?

**Comment by jordanpadams** [comment]
@rchenatjpl can you help point us to a bundle here that we can add to our basic continuous deployment ingestion pipeline?

**Comment by rchenatjpl** [comment]
In this one, the version_id went from 1.0 to 2.0, but the filenames didn't change, so it would only matter to you if you had previously ingested 1.0, which I'm attaching here.
https://pds-atmospheres.nmsu.edu/PDS/data/PDS4/Mars2020/mars2020_meda/data_calibrated_env/
I'll try to find one later where they left both versions lying around.

[atm.zip](https://github.com/NASA-PDS/pds-api/files/8147530/atm.zip)
.

**Comment by rchenatjpl** [comment]
OK, the previous one is what I would call the norm. Now, NAIF lets all previous collection* sit in the same directory, and the latest .csv makes all earlier released data files Secondary members, and only the latest data files Primary, i.e. if you grepped for "^P," in *.csv, you'd have the correct set with no duplicates.
https://naif.jpl.nasa.gov/pub/naif/pds/pds4/maven/maven_spice/spice_kernels/

IMG also lets previous collection* sit in the same directory, but the .tab (not .csv) simply list everything as Primary every time, i.e. if there were N versions and you took the union of them all, you'd have N copies of whatever's in v1.
https://pds-imaging.jpl.nasa.gov/data/nsyt/insight_cameras/data/

I can't think of other implementations.

**Comment by jordanpadams** [comment]
@rchenatjpl for this ticket, after discussions today, could you help us produce a more curated test bundle based upon the criteria updated in the original issue description.

the spice kernel bundle may be a good one if we can maybe version the bundle a couple times and shrink down all the versions (we want to keep the data set somewhat small so we can easily transfer and test with it)

**Comment by tloubrieu-jpl** [comment]
@jordanpadams @rchenatjpl for the current test we are using this bundle https://pds-gamma.jpl.nasa.gov/data/pds4/test-data/registry/urn-nasa-pds-insight_rad.tar.gz

If we can re-use it (by makes some new versions of it which makes us meet the requirements of this ticket) I could more easily keep the already developed tests in postman. But this is a detail...

**Comment by tloubrieu-jpl** [comment]
@al-niessner is having this requirements:
3 bundles versions
5 collections versions
7 product versions

@jordanpadams @rchenatjpl Does it make sense (PDS4-wise) to have 7 versions of a products and only 3 versions of the containing bundle ?

**Comment by jordanpadams** [comment]
@tloubrieu-jpl updated the ticket. It needs to number the other way.

7 bundle version, 5 collection versions, 3 product version. Cannot go the other way

**Comment by tloubrieu-jpl** [comment]
Thanks @jordanpadams , then @rchenatjpl I was thinking we could have 7 versions of the same bundle in 7 zip files which full fill the other requirements on collections and products versions. Then we will be able to use harvest to load the 7 versions of the bundle.

**Comment by rchenatjpl** [comment]
@jordanpadams @tloubrieu-jpl to answer the most recent question, I think the norm (maybe 50%) for bundles is for the bundle version change if new collections are added, i.e. rarely; collection versions to change as new data comes in, i.e. often; product versions to change for reprocessings or fixes, i.e. rarely for observational products.  In practice, many bundles bump the version with every delivery - those probably bump the collection versions as well.

**Comment by jordanpadams** [comment]
Thanks @rchenatjpl . Copy that. For this test data set it is to cover the common and corner cases all in one.

**Comment by jordanpadams** [comment]
@rchenatjpl does this seem reasonable? do you need any more info from us on this?

**Comment by rchenatjpl** [comment]
Sorry, I had review deadlines. This is now #1.

**Comment by rchenatjpl** [comment]
OK, here's what I consider the normal case. Feel free to discuss whatever. I'll come up with other strings of versions.

**Comment by rchenatjpl** [comment]
Oh, maybe the file was too large. 100+MB. I copied it to 
pds-prod1:/home/rchen/Archive.zip
I can replace the data files if desired

**Comment by jordanpadams** [comment]
thanks @rchenatjpl

**Comment by rchenatjpl** [comment]
The NAIF way. There's at least one more way of versioning that I want to include later.
[Archive.zip](https://github.com/NASA-PDS/pds-api/files/8578460/Archive.zip)

**Comment by jordanpadams** [comment]
@rchenatjpl is there any way you could help us "curate" a custom data set to meet the requirements from the ticket description? in other words, we are looking for a test data set we can use over and over again to support our various versioning test cases, but we don't want something that is ginormous and takes a long while to ingest.

**Comment by rchenatjpl** [comment]
@jordanpadams Oh, man, I thought I had, i.e. the .zip on pds-prod1 and Archive.zip two messages ago. Is there something more you want from the normal case?

**Comment by jordanpadams** [comment]
Added here https://pds.nasa.gov/data/pds4/test-data/custom-datasets/
