### ISSUE TITLE
Identify and ingest 1 or more products with multiple versions

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#98]
For all existing API end-points, except for the livid resolver, we want manage a suffix `/all`.

When applied to the end-point, this suffix will modify the query behavior to return all the existing versions of matching products, instead of the default behavior whic is to only return the latest.

API End-points the '/all' suffix applies to are:
/bundles
/bundles/{lid}
/bundles/{lid}/collections
/bundles/{lidvid}/collections
/bundles/{lid}/products
/bundles/{lidvid}/products
/collections
/collections/{lid}
/collections/{lid}/products
/collections/{lidvid}/products
/collections/{lid}/bundles
/collections/{lidvid}/bundles
/products
/products/{lid}
/products/{lid}/collections
/products/{lidvid}/collections
/products/{lid}/bundles
/products/{lidvid}/bundles

(If I missed any, just add them !)

**Comment by jordanpadams** [comment]
@rchenatjpl same here

**Comment by rchenatjpl** [comment]
The only non version 1.0 data (or docs) I've reviewed that are actually live are PSI ones like https://sbn.psi.edu/pds/resource/lc.html
Few data files grow like that, right? And reprocessing are uncommon. I'll guess docs get revised, but I searched a bit and couldn't find any.

**Comment by jordanpadams** [comment]
#97 should suffice for this
